var _ = require("../../comm/code/code.js");
module.exports = {
  CODE_RET_ERR: -1,
  CODE_RET_FEATURE_ERR: -2,
  CODE_RET_UPDATE_ERR: -3,
  CODE_RET_SEARCH_ERR: -4,
  CODE_RET_DEL_ERR: -5,
  CODE_RET_PLATFORM_WRONG: -8,
  CODE_RET_CHANNEL_WRONG: -9,
  CODE_RET_SERVER_ERR: -13,
  CODE_RET_NO_RESULT: -14,
  CODE_RET_GET_CLIENT_ID_ERR: -16,
  CODE_RET_INVALID_REQ: -17,
  RET_INVALID_APPID: -18,
  RET_AUTH_ERR: -19,
  CODE_RISK_TOKEN_INVALID_1: 4,
  CODE_RISK_TOKEN_INVALID_2: 6,
  commCode: _,
  castDfpCode: function (_) {
    return -22e3 - _
  },
  castRiskCode: function (_) {
    return -32e3 - _
  },
  ERROR_BIZ_INIT: 1000100,
  ERROR_BIZ_TICKET: 100200,
  ERROR_BIZ_TIMES_LIMIT: -1000201,
  ERROR_BIZ_FAILD_LIMIT: -1000202,
  ERROR_BIZ_DETECT: -1000300,
  ERROR_BIZ_DETECT_NOTICKET: -1000301,
  ERROR_BIZ_TIME_OUT: -1000302,
  ERROR_BIZ_TICKET_TIME_OUT: -1000303,
  ERROR_BIZ_INIT_TIME_OUT: -1000304,
  ERROR_BIZ_TICKET_FAILD: -1000305,
  ERROR_BIZ_INIT_ARGS_INVALID: -1000306,
  ERROR_ACTIVATE_SIGN_INVALID_PARAM: -1000309,
  ERROR_ACTIVATE_SIGN_NO_SIGN_KEY: -1000310,
  ERROR_ACTIVATE_SIGN_NO_MATCH_SIGN_KEY: -1000311,
  ERROR_SIGN_EMPTY_PARAM: -1000312,
  ERROR_SIGN_BEFORE_ACTIVATE: -1000313,
  ERROR_SIGN_INVALID_SIGN_TOKEN: -1000314,
  ERROR_BIZ_MISS_NODE: -1000315,
  ERROR_BIZ_CANVAS_CRASH: -1000316,
  ERROR_BIZ_FEATURE_TIMEOUT: -1000318,
  ERROR_BIZ_FEATURE_CRASH: -1000319,
  ERROR_BIZ_FEATURE_FAILD: -1000320,
  ERROR_BIZ_API_FAILD: -1000321,
  isExternalFactors: function (_) {
    return _ == this.CODE_RET_ERR || _ == this.CODE_RET_FEATURE_ERR || _ == this.CODE_RET_UPDATE_ERR || _ == this.CODE_RET_SEARCH_ERR || _ == this.CODE_RET_DEL_ERR || _ == this.CODE_RET_PLATFORM_WRONG || _ == this.CODE_RET_CHANNEL_WRONG || _ == this.CODE_RET_SERVER_ERR || _ == this.CODE_RET_NO_RESULT || _ == this.CODE_RET_GET_CLIENT_ID_ERR || _ == this.CODE_RET_INVALID_REQ || _ == this.RET_INVALID_APPID || _ == this.RET_AUTH_ERR
  }
};